apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  labels:
    cluster: admin
    type: lgtm
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: 1.16.*
    helm:
      values: |
        global:
          dnsService: coredns
          extraEnvFrom:
            - secretRef: 
                name: s3-credentials

        ingester:
          replicas: 3
          topologySpreadConstraints: {}
          affinity: {}
          extraEnvFrom:
            - secretRef: 
                name: s3-credentials

        distributor:
          replicas: 3
          topologySpreadConstraints: {}
          affinity: {}
          extraEnvFrom:
            - secretRef: 
                name: s3-credentials

        compactor:
          replicas: 2
          topologySpreadConstraints: {}
          affinity: {}
          extraEnvFrom:
            - secretRef: 
                name: s3-credentials

        querier:
          replicas: 1
          topologySpreadConstraints: {}
          affinity: {}
          extraEnvFrom:
            - secretRef: 
                name: s3-credentials

        queryFrontend:
          replicas: 1
          topologySpreadConstraints: {}
          affinity: {}
          extraEnvFrom:
            - secretRef: 
                name: s3-credentials

        multitenancyEnabled: true
        storage:
          trace:
            backend: s3
            s3:
              bucket: {{.TempoBucketName}}
              endpoint: s3.fr-par.scw.cloud
              region: fr-par
        
        metaMonitoring:
          serviceMonitor:
            enabled: true
        
        prometheusRule:
          enabled: true

        metricsGenerator:
          enabled: true
          topologySpreadConstraints: {}
          affinity: {}
          extraEnvFrom:
            - secretRef: 
                name: s3-credentials
          config:
            storage:
              remote_write:
                - url: http://mimir-gateway.mimir:9009/api/v1/push
                  send_exemplars: true

        traces:
          otlp:
            http:
              enabled: true
            grpc:
              enabled: true

        gateway:
          enabled: true
          topologySpreadConstraints: {}
          affinity: {}
          ingress:
            enabled: true
            ingressClass: nginx
            hosts:
              - host: "tempo.{{.TLD}}"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: tempo-tls
                hosts:
                  - "tempo.{{.TLD}}"


  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
