apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  labels:
    cluster: admin
    type: requirements
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.*
    helm:
      values: |
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          ingressClassResource:
            default: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
